info_en: "[cluster info]"
info_cn: "[集群信息展示]"
command: obdiag display scene run --scene=observer.cluster
task:
  - version: "[2.0.0.0, 4.0.0.0]"
    steps:
      - type: sql
        sql: "SELECT * FROM oceanbase.v$ob_cluster"
        global: true
  - version: "[4.0.0.0, *]"
    steps:
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_ZONES ORDER BY ZONE;"
        global: true
