info_en: "[lock holder info]"
info_cn: "[查看锁等待]"
command: obdiag display scene run --scene=observer.lock_holder
task:
  - version: "[2.0.0.0, 4.0.0.0]"
    steps:
      - type: sql
        sql: "show variables like 'version_comment';"
        global: true
