info_en: "[table info]"
info_cn: "[表信息展示]"
command: obdiag display scene run --scene=observer.table
task:
  - version: "[2.0.0.0, 4.0.0.0]"
    steps:
      - type: sql
        sql: "show variables like 'version_comment';"
        global: true
